
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

# importing necessary modules
import requests
import zipfile
from io import BytesIO
import os
from pathlib import Path
from  playwright_tests import *



# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Button, PhotoImage, messagebox
import controller
#from playwright_tests import *

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path()


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

# Funções para os botões de vizualização de senha 
def View_pass_router():
    if pass_router.cget('show') == '*':
        pass_router.config(show= '')
    else:
        pass_router.config(show= '*')

def View_pass_pppoe():
    if pass_pppoe.cget('show') == '*':
        pass_pppoe.config(show= '')
    else:
        pass_pppoe.config(show= '*')

def View_pass_wifi():
    if pass_wifi.cget('show') == '*':
        pass_wifi.config(show= '')
    else:
        pass_wifi.config(show= '*')

# Deleta os dados dos campos na interface 
def delete():
    
    user_pppoe.delete(0, "end")
    pass_pppoe.delete(0, "end")
    pass_router.delete(0, "end")
    user_wifi.delete (0, "end") 
    pass_wifi.delete(0, "end")

# Realiza o dowload da nova versão do aplicativo (caso esteja desatualizado)
def atualiza_app():
    showinfo(message='Downloading started')

    #Defining the zip file URL
    url = 'https://github.com/BernardoGatt0/fls/raw/main/APP-T%C3%A9c.zip'

    req = requests.get(url)

    cwd = os.getcwd()
    
    exe = zipfile.ZipFile(BytesIO(req.content))
    exe.extractall(cwd)
    
    #showinfo(message='Downloading Completed')

# Pega os dados da interface e coloca seus valores nas variáveis
def Set_variables():

    senha_roteador = str(pass_router.get())
    ususario_pppoe = str(user_pppoe.get())
    senha_pppoe = str(pass_pppoe.get())
    usuario_wifi = str(user_wifi.get())
    senha_wifi = str(pass_wifi.get())
    
    #retorna uma lista para ser usada na automação
    return senha_roteador, ususario_pppoe, senha_pppoe, usuario_wifi, senha_wifi

"""
    Função do botão "Começar" da interface, chama as funções Set_variables() e rodar()
    passando como parâmetro a lista das variáveis de Set_variables()
"""
def Start():
    if (pass_router.get() != "") & (user_pppoe.get() != "") & (pass_pppoe.get() != "") & (user_wifi.get() != "") & (pass_wifi.get() != ""):
        a = Set_variables()
        roda = messagebox.askokcancel("Aviso!", message="Realizando Configurações\nClique OK para continuar")
        if(roda):
            rodar(a)
        else:
            pass
    else:
        messagebox.showerror("Erro!", message="Preencha todos os campos")

"""
    Função do botão atualiza firmware, chama a função update_firmware()
    são passados como parâmeetros as senhas para acessar o roteador 
"""
def firmware_update():
    senha_pppoe = str(pass_pppoe.get())
    senha_roteador = str(pass_router.get())
    if (pass_pppoe.get() != "" or pass_router.get() != ""):  
        roda = messagebox.askokcancel("Aviso!", message="Realizando Atualização de Firmware\nClique OK para continuar")
        if(roda):
            update_firmware(senha_pppoe, senha_roteador)

        else:
            pass
    else:
        messagebox.showerror("Erro!", message="Insira a senha do Roteador")



# Verifica a versão do aplicativo, caso esteja desatualizado, faz o dowload da nova versão
showinfo('Aviso!', message="Verificando Versão do Aplicativo")
try:
    docara = controller.docara_version()
    ultima = controller.last_version()
    ultima = ultima.upper()
    msg = controller.check_version(docara, ultima)
    
    if msg != None:
        atualiza = messagebox.askokcancel('Aviso!', message=msg)

    if msg =='A versão está desatualizada! Por favor atualize para a nova versão!':
        if atualiza == True:
            atualiza_app()
except:
    pass        
    
# definição e configuração da janela
#=========================A INTERFACE FOI FEITA COM Tkinter Designer===================
# LINK DE USO E EXEMPLOS NO COMEÇO DESTE CÓDIGO

window = Tk()
window.title("APP Técnico")
window.geometry("620x745")
window.configure(bg = "#EEEEEE")


canvas = Canvas(
    window,
    bg = "#EEEEEE",
    height = 745,
    width = 620,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

#-------------------------------------------------------
#------------------Senha do Roteador--------------------

canvas.place(x = 0, y = 0)
canvas.create_text(
    109.99999999999994,
    51.0,
    anchor="nw",
    text="Senha do Roteador:",
    fill="#000000",
    font=("MontserratRoman SemiBold", 14 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry.png"))
entry_bg_1 = canvas.create_image(
    309.99999999999994,
    97.0,
    image=entry_image_1
)
pass_router = Entry(
    bd=0,
    bg="#FFFFFF",
    show='*',
    highlightthickness=0
)
pass_router.insert(0, "12345678")
pass_router.place(
    x=117.99999999999994,
    y=78.0,
    width=384.0,
    height=38.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_olho.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=View_pass_router,
    relief="flat"
)
button_1.place(
    x=474.99999999999994,
    y=87.0,
    width=24.0,
    height=22.0
)

#-------------------------------------------------------
#-------------Conectar-se à internet--------------------

canvas.create_text(
    212.99999999999994,
    144.0,
    anchor="nw",
    text="Conectar-se à Internet",
    fill="#000000",
    font=("MontserratRoman Bold", 18 * -1)
)

canvas.create_text(
    109.99999999999994,
    179.0,
    anchor="nw",
    text="Usuário PPPoe:",
    fill="#000000",
    font=("MontserratRoman SemiBold", 14 * -1)
)
canvas.create_text(
    376.99999999999994,
    218.0,
    anchor="nw",
    text="@tcheturbo.com.br",
    fill="#000000",
    font=("MontserratRoman Regular", 12 * -1)
)
entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_tche.png"))
entry_bg_3 = canvas.create_image(
    309.99999999999994,
    225.0,
    image=entry_image_3
)
user_pppoe = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
user_pppoe.place(
    x=117.99999999999994,
    y=206.0,
    width=250.0,
    height=38.0
)

canvas.create_text(
    109.99999999999994,
    254.0,
    anchor="nw",
    text="Senha PPPoe:",
    fill="#000000",
    font=("MontserratRoman SemiBold", 14 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry.png"))
entry_bg_2 = canvas.create_image(
    309.99999999999994,
    300.0,
    image=entry_image_2
)
pass_pppoe = Entry(
    bd=0,
    bg="#FFFFFF",
    show='*',
    highlightthickness=0
)
pass_pppoe.place(
    x=117.99999999999994,
    y=281.0,
    width=384.0,
    height=38.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_olho.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=View_pass_pppoe,
    relief="flat"
)
button_2.place(
    x=474.99999999999994,
    y=290.0,
    width=24.0,
    height=22.0
)

#-------------------------------------------------------
#-------------Configurações de Wi-Fi--------------------

canvas.create_text(
    198.99999999999994,
    346.0,
    anchor="nw",
    text="Configurações de Wi-Fi",
    fill="#000000",
    font=("MontserratRoman Bold", 18 * -1)
)

canvas.create_text(
    109.99999999999994,
    374.0,
    anchor="nw",
    text="SSID:",
    fill="#000000",
    font=("MontserratRoman SemiBold", 14 * -1)
)
entry_image_5 = PhotoImage(
    file=relative_to_assets("entry.png"))
entry_bg_5 = canvas.create_image(
    309.99999999999994,
    420.0,
    image=entry_image_5
)
user_wifi = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
user_wifi.place(
    x=117.99999999999994,
    y=401.0,
    width=384.0,
    height=38.0
)

canvas.create_text(
    109.99999999999994,
    449.0,
    anchor="nw",
    text="Senha Wi-Fi:",
    fill="#000000",
    font=("MontserratRoman SemiBold", 14 * -1)
)
entry_image_4 = PhotoImage(
    file=relative_to_assets("entry.png"))
entry_bg_4 = canvas.create_image(
    309.99999999999994,
    495.0,
    image=entry_image_4
)
pass_wifi = Entry(
    bd=0,
    bg="#FFFFFF",
    show='*',
    highlightthickness=0
)
pass_wifi.place(
    x=117.99999999999994,
    y=476.0,
    width=384.0,
    height=38.0
)
button_image_3 = PhotoImage(
    file=relative_to_assets("button_olho.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=View_pass_wifi,
    relief="flat"
)
button_3.place(
    x=474.99999999999994,
    y=485.0,
    width=24.0,
    height=22.0
)

#-------------------------------------------------------
#------------------Botões Footer------------------------

button_image_4 = PhotoImage(
    file=relative_to_assets("button_comecar.png"))
button_validar = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=Start,
    relief="flat"
)
button_validar.place(
    x=247.99999999999994,
    y=618.0,
    width=141.0,
    height=48.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_limpar.png"))
button_limpar = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=delete,
    relief="flat"
)
button_limpar.place(
    x=192.99999999999994,
    y=549.0,
    width=119.0,
    height=40.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_firmware.png"))
start_button = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    state="active",
    command=firmware_update,
    relief="flat"
)
start_button.place(
    x=325.99999999999994,
    y=549.0,
    width=119.0,
    height=40.0
    
)
"""x=253.99999999999994,
    y=621.0,
    width=130.0,
    height=50.0"""

   

window.resizable(False, False)
window.mainloop()